server:
  port: 8080
spring:
  application:
    name: spring-rest-security
  profiles:
    active: default
  datasource:
    url: jdbc:postgresql://localhost:5432/cybertek_db
    username: postgres
    password: M_aliona1995
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
    data: classpath:data.sql
  jpa:
    properies:
      hibernate:
       dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
       ddl-auto: create
    show-sql: false
security:
  jwt:
    security-key: cybertek

